### ISSUE TITLE
Vaults are broken

### ISSUE THREAD

**Issue by quiquelhappy** [MinecraftWars/Gringotts#170] opened 2018-03-31 13:12 UTC
Vaults are not working, also, the deposit or withdraw methos are not working either.
Could someone fix this please?

**Comment by fjeddy** [comment] 2018-08-12 01:42
Same here, running Minecraft 1.13

Get a message saying that the emeralds were added, but they are just turned into blocks in my inventory, and the amount is still 0.

**Comment by ttocsneb** [comment] 2019-04-24 22:17
I have found that vaults/enderchests do work; the issue is with how gringotts interprets your inventory.  I think your inventory is considered to be a vault which allows it to be used in transactions and show in the `/money` command.

When you run the command `/money withdraw X`, X amount of emeralds will be sent to your inventory from one of your vaults as it should.  However, when you run the command `/money deposit X`, X amount of money is deposited into a vault, it's just that it treats your inventory as a vault, so it will be taken out of your inventory, then put back into your inventory. Which is why it will be changed into blocks.

I don't know anything about how gringotts works under the hood, but I bet that if it were to somehow not treat the player's inventory as a vault when depositing, the issue might be resolved.

**Comment by bundabrg** [comment] 2019-09-21 13:52
Duplicate of #164

**Closed by bundabrg** 2019-09-21 13:52 UTC
