### ISSUE TITLE
Issue with /money pay 100 <playername>

### ISSUE THREAD

**Issue by lvavila** [MinecraftWars/Gringotts#197] opened 2019-04-19 04:13 UTC
Shows 0 payed to playername with no other action.  Using 1.13.2 now.  Everything else works fine.  Love plugin, hope it continues with 1.14.  Diamonds:$100 quartz:$10

**Comment by VaiTon** [comment] 2019-04-20 17:28
Duplicate of #193.

**Comment by lvavila** [comment] 2019-04-21 01:16
Observation in code (GringottsAbstractExecutor)

Does this transaction complete successfully if taxes are disabled?   

TransactionResult result = playerAccount.send(value).withTaxes().to(eco.player(recipientName));
Obviously a SUCCESS is being passed back but formattedValue is 0.00.

**Comment by VaiTon** [comment] 2019-04-21 11:14
Even if it doesn't complete successfully and the returned value is `SUCCESS` the `formattedValue` should be the same as the parameter value. (See [this ](https://github.com/MinecraftWars/Gringotts/blob/master/src/main/java/org/gestern/gringotts/commands/GringottsAbstractExecutor.java#L51)line)

I'm going to investigate this.

**Comment by lvavila** [comment] 2019-04-21 17:47
Thanks for the attention.  I hope you move forward with 1.14 support for if you do I will contribute either through donations or code additions to your project as I am a professional C# developer aspired in having Java in my tool belt. As a new survival 1.13.2 server owner, I find your project different and motivating.

**Comment by jastice** [comment] 2019-04-24 13:13
Thanks for looking into it, @lvavila 
Code contributions and fixes are very welcome

**Comment by flanigomik** [comment] 2019-05-22 19:31
this is still an issue with the 1.14 build, somebody else linked a 1.13 compatible build here;
https://github.com/bundabrg/Gringotts/releases/tag/v3.0.0-preview.1
love the plugin but it is useless without being able to pay people.

**Closed** 2019-09-21 09:17 UTC
